dist: trusty
sudo: required

language: go

go:
  - 1.8.x
  - tip

go_import_path: github.com/containerd/containerd

addons:
  apt:
    packages:
      - btrfs-tools

env:
  - TRAVIS_GOOS=windows TRAVIS_CGO_ENABLED=1
  - TRAVIS_GOOS=linux TRAVIS_CGO_ENABLED=1
  - TRAVIS_GOOS=darwin TRAVIS_CGO_ENABLED=0

install:
  - if [ "$TRAVIS_GOOS" = "windows" ] ; then sudo apt-get install -y gcc-multilib gcc-mingw-w64; export CC=x86_64-w64-mingw32-gcc ; export CXX=x86_64-w64-mingw32-g++ ; fi
  - wget https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-linux-x86_64.zip -O /tmp/protoc-3.1.0-linux-x86_64.zip
  - unzip -o -d /tmp/protobuf /tmp/protoc-3.1.0-linux-x86_64.zip
  - export PATH=$PATH:/tmp/protobuf/bin/
  - go get -u github.com/vbatts/git-validation

script:
  - export GOOS=$TRAVIS_GOOS
  - export CGO_ENABLED=$TRAVIS_CGO_ENABLED
  - GIT_CHECK_EXCLUDE="./vendor" TRAVIS_COMMIT_RANGE="${TRAVIS_COMMIT_RANGE/.../..}" make dco
  - make fmt
  - make vet
  - make binaries
  - if [ "$GOOS" = "linux" ]; then make coverage ; fi
  - if [ "$GOOS" = "linux" ]; then sudo PATH=$PATH GOPATH=$GOPATH make root-coverage ; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
