dist: trusty
sudo: required

language: go

go:
  - 1.7.x
  - 1.8.x
  - tip

go_import_path: github.com/containerd/containerd

addons:
  apt:
    packages:
      - btrfs-tools

env:
  - GOOS=windows
  - GOOS=linux

install:
  - wget https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-linux-x86_64.zip -O /tmp/protoc-3.1.0-linux-x86_64.zip
  - unzip -o -d /tmp/protobuf /tmp/protoc-3.1.0-linux-x86_64.zip
  - export PATH=$PATH:/tmp/protobuf/bin/
  - go get -u github.com/vbatts/git-validation

script:
  - make fmt
  - make binaries
  - make coverage
  - TRAVIS_COMMIT_RANGE="${TRAVIS_COMMIT_RANGE/.../..}" make dco
  - sudo PATH=$PATH GOPATH=$GOPATH make root-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
