dist: trusty
sudo: required

language: go

go:
  - 1.8.x
  - tip

go_import_path: github.com/containerd/containerd

addons:
  apt:
    packages:
      - apparmor
      - libapparmor-dev
      - curl

env:
  - SECCOMP_VERSION=2.3.1 RUNC_COMMIT=d40db12e72a40109dfcf28539f5ee0930d2f0277


install:
  - hack/install-seccomp.sh
  - hack/install-runc.sh
  - go get -u github.com/golang/lint/golint

script:
  - make all
  - sudo make install
  - sudo -E env "PATH=$PATH" "GOPATH=$GOPATH" make test
  - sudo -E env "PATH=$PATH" "GOPATH=$GOPATH" make integration-test
