- hosts: all
  become: yes
  roles:
  - role: config-golang
    go_version: '1.17.5'
    arch: arm64
  tasks:
  - name: Build containerd
    shell:
      cmd: |
        set -xe
        set -o pipefail
        apt-get update
        apt-get install -y btrfs-tools libseccomp-dev git pkg-config

        go version
        make | tee $LOGS_PATH/make.txt

        cp -r ./bin $RESULTS_PATH
      chdir: '{{ zuul.project.src_dir }}'
      executable: /bin/bash
    environment: '{{ global_env }}'
