- hosts: all
  become: yes
  roles:
  - role: config-golang
    go_version: '1.16.3'
    arch: arm64
  tasks:
  - name: Build and test containerd
    shell:
      cmd: |
        set -xe
        set -o pipefail
        apt-get update
        apt-get install -y btrfs-tools libseccomp-dev git pkg-config

        go version
        make build test | tee $LOGS_PATH/make_test.txt
      chdir: '{{ zuul.project.src_dir }}'
      executable: /bin/bash
    environment: '{{ global_env }}'
